### ISSUE TITLE
TODO App "Toggle" always completes top line item

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/incubating-web5-labs#51]
This is not on `main`, but on `upstream` branch `issue-47/update-sdk`:

I clicked ✅ on `3`:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/199891/236672151-67659bbe-da1e-4b0e-82f4-e5edc00f6644.png">

**Comment by ALRubinger** [comment]
Found while debugging, when clicking a ✅:

```
p.vue:148 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dateCreated')
    at Proxy.toggleTodoComplete (App.vue:148:32)
    at onClick (App.vue:185:22)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:345:9)
t
```

**Comment by ALRubinger** [comment]
> [This commit](https://github.com/TBD54566975/incubating-web5-labs/commit/6e81142058ac7c14011ecdcaeb129869792f52e6) resolves the issue of not targeting the correct todo item. Still to do is identify why queried records don't seem to reflect changes made to an updated record. Updating a record returns the expected updated record, but querying seems to return records in their initial state.

Rebased as c929cc3; works great!
